local Cache = require("nvim_translate.cache")

describe("Cache", function()
  it("stores and retrieves values", function()
    local c = Cache.new(10)
    c:set("hello", "world")
    assert.are.equal("world", c:get("hello"))
  end)

  it("returns nil for missing keys", function()
    local c = Cache.new(10)
    assert.is_nil(c:get("missing"))
  end)

  it("reports size correctly", function()
    local c = Cache.new(10)
    assert.are.equal(0, c:size())
    c:set("a", 1)
    c:set("b", 2)
    assert.are.equal(2, c:size())
  end)

  it("evicts oldest entry when full", function()
    local c = Cache.new(3)
    c:set("a", 1)
    c:set("b", 2)
    c:set("c", 3)
    -- cache is full, adding one more should evict "a"
    c:set("d", 4)
    assert.is_nil(c:get("a"))
    assert.are.equal(2, c:get("b"))
    assert.are.equal(3, c:get("c"))
    assert.are.equal(4, c:get("d"))
    assert.are.equal(3, c:size())
  end)

  it("promotes accessed entries (LRU behavior)", function()
    local c = Cache.new(3)
    c:set("a", 1)
    c:set("b", 2)
    c:set("c", 3)
    -- access "a" so it becomes most recently used
    c:get("a")
    -- adding "d" should evict "b" (now the least recently used)
    c:set("d", 4)
    assert.are.equal(1, c:get("a"))
    assert.is_nil(c:get("b"))
    assert.are.equal(3, c:get("c"))
    assert.are.equal(4, c:get("d"))
  end)

  it("does not duplicate keys on set", function()
    local c = Cache.new(10)
    c:set("a", 1)
    c:set("a", 2) -- should be ignored (existing key)
    assert.are.equal(1, c:get("a"))
    assert.are.equal(1, c:size())
  end)

  it("handles single-element cache", function()
    local c = Cache.new(1)
    c:set("a", 1)
    assert.are.equal(1, c:get("a"))
    c:set("b", 2)
    assert.is_nil(c:get("a"))
    assert.are.equal(2, c:get("b"))
    assert.are.equal(1, c:size())
  end)

  it("promotes last element without error", function()
    local c = Cache.new(3)
    c:set("a", 1)
    c:set("b", 2)
    c:set("c", 3)
    -- "c" is already at end, promote should be a no-op
    local val = c:get("c")
    assert.are.equal(3, val)
    -- all still accessible
    assert.are.equal(1, c:get("a"))
    assert.are.equal(2, c:get("b"))
  end)

  it("evicts in correct LRU order across multiple cycles", function()
    local c = Cache.new(2)
    c:set("a", 1)
    c:set("b", 2)
    -- access "a" to make "b" the LRU
    c:get("a")
    c:set("c", 3) -- evicts "b"
    assert.is_nil(c:get("b"))
    assert.are.equal(1, c:get("a"))
    -- now "c" is LRU (we just accessed "a")
    c:set("d", 4) -- evicts "c"
    assert.is_nil(c:get("c"))
    assert.are.equal(4, c:get("d"))
  end)
end)
